/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PhaseName,
  RecentSalesProvider,
  SalesHistoryResponse,
  ValidationErrorResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PhaseNameFromJSON,
    PhaseNameToJSON,
    RecentSalesProviderFromJSON,
    RecentSalesProviderToJSON,
    SalesHistoryResponseFromJSON,
    SalesHistoryResponseToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface ListRecentSalesRequest {
    itemId?: number | null;
    marketHashName?: string | null;
    phase?: PhaseName | null;
    providers?: Array<RecentSalesProvider> | null;
    minFloat?: number | null;
    maxFloat?: number | null;
    paintSeed?: number | null;
    stickers?: Array<string> | null;
    charms?: string | null;
    currency?: string;
    limit?: number | null;
    cursor?: string | null;
}

/**
 * 
 */
export class SalesApi extends runtime.BaseAPI {

    /**
     * Creates request options for listRecentSales without sending the request
     */
    async listRecentSalesRequestOpts(requestParameters: ListRecentSalesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['itemId'] != null) {
            queryParameters['item_id'] = requestParameters['itemId'];
        }

        if (requestParameters['marketHashName'] != null) {
            queryParameters['market_hash_name'] = requestParameters['marketHashName'];
        }

        if (requestParameters['phase'] != null) {
            queryParameters['phase'] = requestParameters['phase'];
        }

        if (requestParameters['providers'] != null) {
            queryParameters['providers'] = requestParameters['providers'];
        }

        if (requestParameters['minFloat'] != null) {
            queryParameters['min_float'] = requestParameters['minFloat'];
        }

        if (requestParameters['maxFloat'] != null) {
            queryParameters['max_float'] = requestParameters['maxFloat'];
        }

        if (requestParameters['paintSeed'] != null) {
            queryParameters['paint_seed'] = requestParameters['paintSeed'];
        }

        if (requestParameters['stickers'] != null) {
            queryParameters['stickers'] = requestParameters['stickers'];
        }

        if (requestParameters['charms'] != null) {
            queryParameters['charms'] = requestParameters['charms'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/sales`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return recent sales across providers with recent-sales support, newest first.  With no filters, returns the global recent-sales feed ordered by sale time (most recent first). Optional filters narrow the results: - `item_id` — restrict to one catalog item (its canonical market_hash_name and phase are used) - `market_hash_name` (+ optional `phase`) — restrict to one item by name - `min_float` / `max_float` — restrict to a float-value range - `paint_seed` — restrict to an exact paint seed - `stickers` — restrict to sales containing every requested sticker name - `charms` — restrict to sales containing one requested charm name - `providers` — restrict to specific sales-capable provider keys - `currency` — convert values to the target currency  Pagination: - `limit` sets the page size (max 100 for Pro, 1000 for Quant) - pass `cursor` from the previous response\'s `pagination.next_cursor` to page through results; `pagination.total` is `-1` (count intentionally skipped)  Behavior: - recent-sales data refreshes roughly once every 24 hours, so results may be up to a day old  Response: - request metadata, providers queried, and a cursor pagination footer - sales records with sticker, charm, and inspect metadata when available
     * List Recent Sales
     */
    async listRecentSalesRaw(requestParameters: ListRecentSalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SalesHistoryResponse>> {
        const requestOptions = await this.listRecentSalesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalesHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Return recent sales across providers with recent-sales support, newest first.  With no filters, returns the global recent-sales feed ordered by sale time (most recent first). Optional filters narrow the results: - `item_id` — restrict to one catalog item (its canonical market_hash_name and phase are used) - `market_hash_name` (+ optional `phase`) — restrict to one item by name - `min_float` / `max_float` — restrict to a float-value range - `paint_seed` — restrict to an exact paint seed - `stickers` — restrict to sales containing every requested sticker name - `charms` — restrict to sales containing one requested charm name - `providers` — restrict to specific sales-capable provider keys - `currency` — convert values to the target currency  Pagination: - `limit` sets the page size (max 100 for Pro, 1000 for Quant) - pass `cursor` from the previous response\'s `pagination.next_cursor` to page through results; `pagination.total` is `-1` (count intentionally skipped)  Behavior: - recent-sales data refreshes roughly once every 24 hours, so results may be up to a day old  Response: - request metadata, providers queried, and a cursor pagination footer - sales records with sticker, charm, and inspect metadata when available
     * List Recent Sales
     */
    async listRecentSales(requestParameters: ListRecentSalesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SalesHistoryResponse> {
        const response = await this.listRecentSalesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
