/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BuyOrderItem } from './BuyOrderItem';
import {
    BuyOrderItemFromJSON,
    BuyOrderItemFromJSONTyped,
    BuyOrderItemToJSON,
    BuyOrderItemToJSONTyped,
} from './BuyOrderItem';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { PricesMeta } from './PricesMeta';
import {
    PricesMetaFromJSON,
    PricesMetaFromJSONTyped,
    PricesMetaToJSON,
    PricesMetaToJSONTyped,
} from './PricesMeta';

/**
 * Bids response with metadata and pagination.
 * @export
 * @interface BidsResponse
 */
export interface BidsResponse {
    /**
     * Response metadata for this payload.
     * @type {PricesMeta}
     * @memberof BidsResponse
     */
    meta: PricesMeta;
    /**
     * List of returned items.
     * @type {Array<BuyOrderItem>}
     * @memberof BidsResponse
     */
    items: Array<BuyOrderItem>;
    /**
     * Offset pagination metadata.
     * @type {PaginationMeta}
     * @memberof BidsResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the BidsResponse interface.
 */
export function instanceOfBidsResponse(value: object): value is BidsResponse {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function BidsResponseFromJSON(json: any): BidsResponse {
    return BidsResponseFromJSONTyped(json, false);
}

export function BidsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BidsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': PricesMetaFromJSON(json['meta']),
        'items': ((json['items'] as Array<any>).map(BuyOrderItemFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function BidsResponseToJSON(json: any): BidsResponse {
    return BidsResponseToJSONTyped(json, false);
}

export function BidsResponseToJSONTyped(value?: BidsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PricesMetaToJSON(value['meta']),
        'items': ((value['items'] as Array<any>).map(BuyOrderItemToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

