/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketHistoryChartSeries } from './MarketHistoryChartSeries';
import {
    MarketHistoryChartSeriesFromJSON,
    MarketHistoryChartSeriesFromJSONTyped,
    MarketHistoryChartSeriesToJSON,
    MarketHistoryChartSeriesToJSONTyped,
} from './MarketHistoryChartSeries';
import type { MarketHistoryChartMeta } from './MarketHistoryChartMeta';
import {
    MarketHistoryChartMetaFromJSON,
    MarketHistoryChartMetaFromJSONTyped,
    MarketHistoryChartMetaToJSON,
    MarketHistoryChartMetaToJSONTyped,
} from './MarketHistoryChartMeta';

/**
 * Response envelope for GET /v1/market/history/chart (Quant only).
 * @export
 * @interface MarketHistoryChartResponse
 */
export interface MarketHistoryChartResponse {
    /**
     * Response metadata for this payload.
     * @type {MarketHistoryChartMeta}
     * @memberof MarketHistoryChartResponse
     */
    meta: MarketHistoryChartMeta;
    /**
     * Per-provider daily price-point series.
     * @type {Array<MarketHistoryChartSeries>}
     * @memberof MarketHistoryChartResponse
     */
    series?: Array<MarketHistoryChartSeries>;
}

/**
 * Check if a given object implements the MarketHistoryChartResponse interface.
 */
export function instanceOfMarketHistoryChartResponse(value: object): value is MarketHistoryChartResponse {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function MarketHistoryChartResponseFromJSON(json: any): MarketHistoryChartResponse {
    return MarketHistoryChartResponseFromJSONTyped(json, false);
}

export function MarketHistoryChartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketHistoryChartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': MarketHistoryChartMetaFromJSON(json['meta']),
        'series': json['series'] == null ? undefined : ((json['series'] as Array<any>).map(MarketHistoryChartSeriesFromJSON)),
    };
}

export function MarketHistoryChartResponseToJSON(json: any): MarketHistoryChartResponse {
    return MarketHistoryChartResponseToJSONTyped(json, false);
}

export function MarketHistoryChartResponseToJSONTyped(value?: MarketHistoryChartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': MarketHistoryChartMetaToJSON(value['meta']),
        'series': value['series'] == null ? undefined : ((value['series'] as Array<any>).map(MarketHistoryChartSeriesToJSON)),
    };
}

