/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata for /v1/market/history/chart.
 * @export
 * @interface MarketHistoryChartMeta
 */
export interface MarketHistoryChartMeta {
    /**
     * Normalized catalog item ID.
     * @type {number}
     * @memberof MarketHistoryChartMeta
     */
    itemId: number;
    /**
     * Canonical market hash name for the item.
     * @type {string}
     * @memberof MarketHistoryChartMeta
     */
    marketHashName: string;
    /**
     * Target currency code for returned prices.
     * @type {string}
     * @memberof MarketHistoryChartMeta
     */
    currency: string;
    /**
     * ISO 8601 UTC start of the returned window.
     * @type {Date}
     * @memberof MarketHistoryChartMeta
     */
    start: Date;
    /**
     * ISO 8601 UTC end of the returned window.
     * @type {Date}
     * @memberof MarketHistoryChartMeta
     */
    end: Date;
    /**
     * Provider keys actually returned (those with >=1 point in range).
     * @type {Array<string>}
     * @memberof MarketHistoryChartMeta
     */
    providers?: Array<string>;
}

/**
 * Check if a given object implements the MarketHistoryChartMeta interface.
 */
export function instanceOfMarketHistoryChartMeta(value: object): value is MarketHistoryChartMeta {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('marketHashName' in value) || value['marketHashName'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function MarketHistoryChartMetaFromJSON(json: any): MarketHistoryChartMeta {
    return MarketHistoryChartMetaFromJSONTyped(json, false);
}

export function MarketHistoryChartMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketHistoryChartMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'marketHashName': json['market_hash_name'],
        'currency': json['currency'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'providers': json['providers'] == null ? undefined : json['providers'],
    };
}

export function MarketHistoryChartMetaToJSON(json: any): MarketHistoryChartMeta {
    return MarketHistoryChartMetaToJSONTyped(json, false);
}

export function MarketHistoryChartMetaToJSONTyped(value?: MarketHistoryChartMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'currency': value['currency'],
        'start': value['start'].toISOString(),
        'end': value['end'].toISOString(),
        'providers': value['providers'],
    };
}

