/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One daily price point for a provider series.
 * @export
 * @interface MarketHistoryChartPoint
 */
export interface MarketHistoryChartPoint {
    /**
     * UTC day bucket as a Unix timestamp (seconds, midnight).
     * @type {number}
     * @memberof MarketHistoryChartPoint
     */
    t: number;
    /**
     * Closing price in minor units of the response currency.
     * @type {number}
     * @memberof MarketHistoryChartPoint
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof MarketHistoryChartPoint
     */
    qty?: number | null;
}

/**
 * Check if a given object implements the MarketHistoryChartPoint interface.
 */
export function instanceOfMarketHistoryChartPoint(value: object): value is MarketHistoryChartPoint {
    if (!('t' in value) || value['t'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function MarketHistoryChartPointFromJSON(json: any): MarketHistoryChartPoint {
    return MarketHistoryChartPointFromJSONTyped(json, false);
}

export function MarketHistoryChartPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketHistoryChartPoint {
    if (json == null) {
        return json;
    }
    return {
        
        't': json['t'],
        'price': json['price'],
        'qty': json['qty'] == null ? undefined : json['qty'],
    };
}

export function MarketHistoryChartPointToJSON(json: any): MarketHistoryChartPoint {
    return MarketHistoryChartPointToJSONTyped(json, false);
}

export function MarketHistoryChartPointToJSONTyped(value?: MarketHistoryChartPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        't': value['t'],
        'price': value['price'],
        'qty': value['qty'],
    };
}

