/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketHistoryChartPoint } from './MarketHistoryChartPoint';
import {
    MarketHistoryChartPointFromJSON,
    MarketHistoryChartPointFromJSONTyped,
    MarketHistoryChartPointToJSON,
    MarketHistoryChartPointToJSONTyped,
} from './MarketHistoryChartPoint';

/**
 * Per-provider daily price-point series.
 * @export
 * @interface MarketHistoryChartSeries
 */
export interface MarketHistoryChartSeries {
    /**
     * Provider key.
     * @type {string}
     * @memberof MarketHistoryChartSeries
     */
    provider: string;
    /**
     * Daily points ordered by ascending bucket.
     * @type {Array<MarketHistoryChartPoint>}
     * @memberof MarketHistoryChartSeries
     */
    data?: Array<MarketHistoryChartPoint>;
}

/**
 * Check if a given object implements the MarketHistoryChartSeries interface.
 */
export function instanceOfMarketHistoryChartSeries(value: object): value is MarketHistoryChartSeries {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function MarketHistoryChartSeriesFromJSON(json: any): MarketHistoryChartSeries {
    return MarketHistoryChartSeriesFromJSONTyped(json, false);
}

export function MarketHistoryChartSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketHistoryChartSeries {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MarketHistoryChartPointFromJSON)),
    };
}

export function MarketHistoryChartSeriesToJSON(json: any): MarketHistoryChartSeries {
    return MarketHistoryChartSeriesToJSONTyped(json, false);
}

export function MarketHistoryChartSeriesToJSONTyped(value?: MarketHistoryChartSeries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MarketHistoryChartPointToJSON)),
    };
}

