/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaleRecordDetail } from './SaleRecordDetail';
import {
    SaleRecordDetailFromJSON,
    SaleRecordDetailFromJSONTyped,
    SaleRecordDetailToJSON,
    SaleRecordDetailToJSONTyped,
} from './SaleRecordDetail';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { SalesMeta } from './SalesMeta';
import {
    SalesMetaFromJSON,
    SalesMetaFromJSONTyped,
    SalesMetaToJSON,
    SalesMetaToJSONTyped,
} from './SalesMeta';

/**
 * Recent Sales response with request metadata.
 * @export
 * @interface SalesHistoryResponse
 */
export interface SalesHistoryResponse {
    /**
     * Response metadata for this payload.
     * @type {SalesMeta}
     * @memberof SalesHistoryResponse
     */
    meta: SalesMeta;
    /**
     * List of returned items.
     * @type {Array<SaleRecordDetail>}
     * @memberof SalesHistoryResponse
     */
    items: Array<SaleRecordDetail>;
    /**
     * Cursor pagination footer for this page.
     * @type {PaginationMeta}
     * @memberof SalesHistoryResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the SalesHistoryResponse interface.
 */
export function instanceOfSalesHistoryResponse(value: object): value is SalesHistoryResponse {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function SalesHistoryResponseFromJSON(json: any): SalesHistoryResponse {
    return SalesHistoryResponseFromJSONTyped(json, false);
}

export function SalesHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': SalesMetaFromJSON(json['meta']),
        'items': ((json['items'] as Array<any>).map(SaleRecordDetailFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function SalesHistoryResponseToJSON(json: any): SalesHistoryResponse {
    return SalesHistoryResponseToJSONTyped(json, false);
}

export function SalesHistoryResponseToJSONTyped(value?: SalesHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': SalesMetaToJSON(value['meta']),
        'items': ((value['items'] as Array<any>).map(SaleRecordDetailToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

