/* tslint:disable */
/* eslint-disable */
/**
 * CS2Cap
 * CS2Cap aggregates and analyzes Counter-Strike 2 marketplace data across multiple providers via a unified REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Filter metadata for sales endpoint.
 * @export
 * @interface SalesFiltersMeta
 */
export interface SalesFiltersMeta {
    /**
     * 
     * @type {number}
     * @memberof SalesFiltersMeta
     */
    itemId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SalesFiltersMeta
     */
    marketHashName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SalesFiltersMeta
     */
    phase?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SalesFiltersMeta
     */
    requestedProviders?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof SalesFiltersMeta
     */
    minFloat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SalesFiltersMeta
     */
    maxFloat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SalesFiltersMeta
     */
    paintSeed?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SalesFiltersMeta
     */
    stickers?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof SalesFiltersMeta
     */
    charms?: string | null;
    /**
     * Maximum number of records returned per page.
     * @type {number}
     * @memberof SalesFiltersMeta
     */
    limit: number;
}

/**
 * Check if a given object implements the SalesFiltersMeta interface.
 */
export function instanceOfSalesFiltersMeta(value: object): value is SalesFiltersMeta {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function SalesFiltersMetaFromJSON(json: any): SalesFiltersMeta {
    return SalesFiltersMetaFromJSONTyped(json, false);
}

export function SalesFiltersMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesFiltersMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'] == null ? undefined : json['item_id'],
        'marketHashName': json['market_hash_name'] == null ? undefined : json['market_hash_name'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'requestedProviders': json['requested_providers'] == null ? undefined : json['requested_providers'],
        'minFloat': json['min_float'] == null ? undefined : json['min_float'],
        'maxFloat': json['max_float'] == null ? undefined : json['max_float'],
        'paintSeed': json['paint_seed'] == null ? undefined : json['paint_seed'],
        'stickers': json['stickers'] == null ? undefined : json['stickers'],
        'charms': json['charms'] == null ? undefined : json['charms'],
        'limit': json['limit'],
    };
}

export function SalesFiltersMetaToJSON(json: any): SalesFiltersMeta {
    return SalesFiltersMetaToJSONTyped(json, false);
}

export function SalesFiltersMetaToJSONTyped(value?: SalesFiltersMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'market_hash_name': value['marketHashName'],
        'phase': value['phase'],
        'requested_providers': value['requestedProviders'],
        'min_float': value['minFloat'],
        'max_float': value['maxFloat'],
        'paint_seed': value['paintSeed'],
        'stickers': value['stickers'],
        'charms': value['charms'],
        'limit': value['limit'],
    };
}

